config/routes.rb
Rails.application.routes.draw do
  get '/todos', to: 'todos#index'
  get '/todos/new'
  get '/todos/list'
  post '/todos', to: 'todos#create'
  get '/todos/:id', to: 'todos#show', as: 'todo'
  get '/todos/:id/edit', to: 'todos#edit', as: 'todo_edit'
  patch 'todos/:id', to: 'todos#update'
  delete '/todos/:id', to: 'todos#destroy'
  get '/todos/:id/complete', to: 'todos#complete', as:'todo_complete'

  root 'todos#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true
  validates :completed, inclusion: { in: [true, false] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  #public method
  def index
    @todo = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.save

    redirect_to todos_path
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(todo_params)
    redirect_to todos_path
  end

  def destroy
    @todo = Todo.find(params[:id]).destroy
    redirect_to todos_path
  end

  def complete
    @todo = Todo.find(params[:id])
    @todo.completed = true
    @todo.save
    redirect_to todos_path
  end

  def list
    @todo = Todo.all
  end

  #Private method
  private
  def todo_params
   params.require(:todo).permit(:description, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'todos/navbar' %>
    <%= yield %>
  </body>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
</html>

app/views/todos/_form.html.erb
<div class="container">
  <%= form_with model: @todo, local: true do |f| %>
  <div class="form-group">
    <%= f.label '¿Qué tienes que hacer?' %>
    <%= f.text_field :description, class: 'form-control', placeholder: 'Descripción' %>
  </div>
  <div class="form-group form-check">
    <%= f.check_box :completed %>
    <%= f.label '¿Completado?' %>
  </div>
  <%= f.submit 'Enviar', class: 'btn btn-dark' %>

  <% end %>
</div>

app/views/todos/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Inicio', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Listado', todos_list_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Nueva tarea', todos_new_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/todos/edit.html.erb
<div class="container">
  <h1 class="mt-5">Edita tu pendiente</h1>
</div>
<%= render 'todos/form' %>

app/views/todos/index.html.erb
<div class="container">
  <h1 class="mt-5">Todas las tareas:</h1>
  <div class="alert alert-success" role="alert">
    <h4 class="alert-heading">¿Quiéres crear una nueva tarea?</h4>
    <%= link_to 'Presiona aquí', todos_new_path, class:'alert-link' %>
  </div>
  <% @todo.each do |todo| %>
  <div class="card mb-3">
    <div class="card-body">
      <h3 class="card-title d-inline"><%= todo.description %></h3>
      <% if todo.completed === true %>
        <%= link_to "Completar", todo_complete_path(todo), class:'badge badge-dark ml-3' %>
      <% else %>
        <%= link_to "Completar", todo_complete_path(todo), class:'badge badge-light ml-3' %>
      <% end %>
      <h6 class="card-subtitle mb-2 mt-2 text-muted">Estado: <%= todo.completed %></h6>
      <%= link_to "Ver", todo_path(todo), target: '_blank', class: 'btn btn-dark'%>
      <%= link_to "Modificar", todo_edit_path(todo), target: '_blank', class: 'btn btn-light'%>
      <%= link_to "Eliminar", todo, method: :delete,  class: 'btn btn-outline-danger' %>
    </div>
  </div>
  <% end %>
</div>

app/views/todos/list.html.erb
<div class="container">
  <h1 class="mb-3 mt-5">Mis pendientes</h1>
  <%= link_to "Crear nueva tarea", todos_path %>
  <div class="row mt-3">
    <div class="col-sm-6">
      <h3>Completados</h3>
      <table class="table">
        <tbody>

          <% @todo.each do |todo| %>
            <% if todo.completed === true %>
            <tr>
              <td><%= todo.description  %></td>
            </tr>
            <% end %>
          <% end %>

        </tbody>
      </table>
    </div>
    <div class="col-sm-6">
      <h3>Pendientes</h3>
      <table class="table">
        <tbody>
          <% @todo.each do |todo| %>
            <% if todo.completed === false %>
            <tr>
              <td><%= todo.description  %></td>
            </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/todos/new.html.erb
<div class="container">
  <h1 class="mt-5">Crea tu pendiente</h1>
</div>
<%= render 'todos/form' %>

app/views/todos/show.html.erb
<div class="container">
  <h1 class="mt-5"><%= @todo.description %></h1>
  <h5 class="text-monospace">Estado: <%= @todo.completed %></h5>
  <%= link_to 'volver', todos_path %>
</div>